services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${NODOS_DB_HOSTNAME}
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
