services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    volumes:
      - .:/app
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${NODOS_DB_HOSTNAME}
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
